// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseConfig() {
  return window['go']['main']['App']['BrowseConfig']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3, arg4);
}

export function SendOTP(arg1) {
  return window['go']['main']['App']['SendOTP'](arg1);
}
