// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseConfig():Promise<string>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<string>;

export function Disconnect():Promise<string>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetStatus():Promise<string>;

export function SaveProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendOTP(arg1:string):Promise<void>;
